// <auto-generated />
using System;
using Enma.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Enma.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EnmaDbContext))]
    [Migration("20260827182006_AddAuditLogs")]
    partial class AddAuditLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Enma.Domain.Auditing.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_membership_id");

                    b.Property<int>("ActorRoleAtOccurrence")
                        .HasColumnType("integer")
                        .HasColumnName("actor_role_at_occurrence");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer")
                        .HasColumnName("entity_type");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("TraceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trace_id");

                    b.Property<string>("_detailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("OrganizationId", "ActorMembershipId", "ActorUserId")
                        .HasDatabaseName("ix_audit_logs_org_actor_membership_id_actor_user_id");

                    b.HasIndex("OrganizationId", "OccurredAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_audit_logs_organization_id_occurred_at_id");

                    b.HasIndex("OrganizationId", "ActorUserId", "OccurredAt", "Id")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("ix_audit_logs_org_actor_user_id_occurred_at_id");

                    b.HasIndex("OrganizationId", "EventType", "OccurredAt", "Id")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("ix_audit_logs_org_event_type_occurred_at_id");

                    b.HasIndex("OrganizationId", "EntityType", "EntityId", "OccurredAt", "Id")
                        .IsDescending(false, false, false, true, true)
                        .HasDatabaseName("ix_audit_logs_org_entity_type_entity_id_occurred_at_id");

                    b.ToTable("audit_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_logs_actor_role_at_occurrence", "actor_role_at_occurrence IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_audit_logs_details_contract", "(event_type IN (1, 2, 12, 16, 17, 21, 22) AND details IS NOT NULL AND jsonb_typeof(details) = 'object') OR (event_type NOT IN (1, 2, 12, 16, 17, 21, 22) AND details IS NULL)");

                            t.HasCheckConstraint("ck_audit_logs_details_size", "details IS NULL OR octet_length(convert_to(details::text, 'UTF8')) <= 8192");

                            t.HasCheckConstraint("ck_audit_logs_entity_type", "entity_type IN (1, 2, 3, 4, 5, 6, 7, 8)");

                            t.HasCheckConstraint("ck_audit_logs_event_entity_type", "(event_type = 1 AND entity_type = 1) OR (event_type IN (2, 3, 4) AND entity_type = 2) OR (event_type IN (5, 6, 7, 8) AND entity_type = 3) OR (event_type IN (9, 10) AND entity_type = 4) OR (event_type IN (11, 12, 13, 14) AND entity_type = 5) OR (event_type IN (15, 16, 17, 18, 19) AND entity_type = 6) OR (event_type IN (20, 21, 22, 23) AND entity_type = 7) OR (event_type = 24 AND entity_type = 8)");

                            t.HasCheckConstraint("ck_audit_logs_event_type", "event_type IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24)");

                            t.HasCheckConstraint("ck_audit_logs_trace_id", "trace_id IS NULL OR (trace_id ~ '^[0-9a-f]{32}$' AND trace_id <> repeat('0', 32))");
                        });
                });

            modelBuilder.Entity("Enma.Domain.Authentication.AuthenticationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expires_at");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CredentialVersionAtIssue")
                        .HasColumnType("bigint")
                        .HasColumnName("credential_version_at_issue");

                    b.Property<DateTimeOffset>("IdleExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("idle_expires_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_authentication_sessions");

                    b.HasIndex("AbsoluteExpiresAt")
                        .HasDatabaseName("ix_authentication_sessions_absolute_expires_at");

                    b.HasIndex("IdleExpiresAt")
                        .HasDatabaseName("ix_authentication_sessions_idle_expires_at");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("ux_authentication_sessions_secret_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_authentication_sessions_user_id");

                    b.ToTable("authentication_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_authentication_sessions_absolute_expires_at", "absolute_expires_at > created_at");

                            t.HasCheckConstraint("ck_authentication_sessions_concurrency_version", "concurrency_version > 0");

                            t.HasCheckConstraint("ck_authentication_sessions_credential_version_at_issue", "credential_version_at_issue > 0");

                            t.HasCheckConstraint("ck_authentication_sessions_idle_expires_at", "idle_expires_at > last_seen_at AND idle_expires_at <= absolute_expires_at");

                            t.HasCheckConstraint("ck_authentication_sessions_last_seen_at", "last_seen_at >= created_at");

                            t.HasCheckConstraint("ck_authentication_sessions_revoked_at", "revoked_at IS NULL OR revoked_at >= created_at");

                            t.HasCheckConstraint("ck_authentication_sessions_secret_hash_length", "octet_length(secret_hash) = 32");
                        });
                });

            modelBuilder.Entity("Enma.Domain.Authentication.EmailVerificationChallenge", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailAtIssue")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email_at_issue");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.HasKey("UserId")
                        .HasName("pk_email_verification_challenges");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_email_verification_challenges_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_email_verification_challenges_token_hash");

                    b.ToTable("email_verification_challenges", null, t =>
                        {
                            t.HasCheckConstraint("ck_email_verification_challenges_expiration", "expires_at > created_at");

                            t.HasCheckConstraint("ck_email_verification_challenges_token_hash_length", "octet_length(token_hash) = 32");
                        });
                });

            modelBuilder.Entity("Enma.Domain.CalendarEvents.CalendarEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_membership_id");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_membership_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("location");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_calendar_events");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_calendar_events_organization_id_id");

                    b.HasIndex("OrganizationId", "CreatedByMembershipId")
                        .HasDatabaseName("ix_calendar_events_org_created_by_membership_id");

                    b.HasIndex("OrganizationId", "StartsAt", "Id")
                        .HasDatabaseName("ix_calendar_events_organization_id_starts_at_id");

                    b.HasIndex("StartsAt", "OrganizationId", "Id")
                        .HasDatabaseName("ix_calendar_events_starts_at_organization_id_id");

                    b.HasIndex("OrganizationId", "AssigneeMembershipId", "StartsAt", "Id")
                        .HasDatabaseName("ix_calendar_events_org_assignee_starts_at_id")
                        .HasFilter("assignee_membership_id IS NOT NULL");

                    b.HasIndex("OrganizationId", "ClientId", "StartsAt", "Id")
                        .HasDatabaseName("ix_calendar_events_org_client_starts_at_id")
                        .HasFilter("client_id IS NOT NULL");

                    b.HasIndex("OrganizationId", "ProcessId", "StartsAt", "Id")
                        .HasDatabaseName("ix_calendar_events_org_process_starts_at_id")
                        .HasFilter("process_id IS NOT NULL");

                    b.ToTable("calendar_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_calendar_events_association", "NOT (client_id IS NOT NULL AND process_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_calendar_events_description_normalized", "description IS NULL OR (description = btrim(description) AND length(description) > 0)");

                            t.HasCheckConstraint("ck_calendar_events_location_normalized", "location IS NULL OR (location = btrim(location) AND length(location) > 0)");

                            t.HasCheckConstraint("ck_calendar_events_time_range", "ends_at > starts_at");

                            t.HasCheckConstraint("ck_calendar_events_title_normalized", "title = btrim(title) AND length(title) > 0");
                        });
                });

            modelBuilder.Entity("Enma.Domain.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_clients_organization_id_id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Enma.Domain.Deadlines.LegalDeadline", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_legal_deadlines");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_legal_deadlines_organization_id_id");

                    b.HasIndex("DueDate", "OrganizationId", "Id")
                        .HasDatabaseName("ix_legal_deadlines_pending_due_date_organization_id_id")
                        .HasFilter("completed_at IS NULL");

                    b.HasIndex("OrganizationId", "DueDate", "Id")
                        .HasDatabaseName("ix_legal_deadlines_organization_id_due_date_id");

                    b.HasIndex("OrganizationId", "ProcessId", "DueDate", "Id")
                        .HasDatabaseName("ix_legal_deadlines_organization_id_process_id_due_date_id");

                    b.ToTable("legal_deadlines", null, t =>
                        {
                            t.HasCheckConstraint("ck_legal_deadlines_completion", "completed_at IS NULL OR completed_at >= created_at");

                            t.HasCheckConstraint("ck_legal_deadlines_title_normalized", "title = btrim(title) AND title <> ''");
                        });
                });

            modelBuilder.Entity("Enma.Domain.Documents.LegalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<byte[]>("ContentHashSha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content_hash_sha256");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("original_file_name");

                    b.Property<Guid?>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoredObjectKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("stored_object_key");

                    b.Property<Guid>("UploadedByMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_membership_id");

                    b.HasKey("Id")
                        .HasName("pk_legal_documents");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_legal_documents_organization_id_id");

                    b.HasIndex("StoredObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ux_legal_documents_stored_object_key");

                    b.HasIndex("OrganizationId", "ClientId")
                        .HasDatabaseName("ix_legal_documents_organization_id_client_id");

                    b.HasIndex("OrganizationId", "ProcessId")
                        .HasDatabaseName("ix_legal_documents_organization_id_process_id");

                    b.HasIndex("OrganizationId", "UploadedByMembershipId")
                        .HasDatabaseName("ix_legal_documents_org_id_uploaded_by_membership_id");

                    b.HasIndex("OrganizationId", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_legal_documents_organization_id_created_at_id");

                    b.ToTable("legal_documents", null, t =>
                        {
                            t.HasCheckConstraint("ck_legal_documents_classification", "NOT (client_id IS NOT NULL AND process_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_legal_documents_content_hash_sha256_length", "octet_length(content_hash_sha256) = 32");

                            t.HasCheckConstraint("ck_legal_documents_content_type", "content_type IN ('application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'image/png', 'image/jpeg')");

                            t.HasCheckConstraint("ck_legal_documents_original_file_name", "char_length(original_file_name) BETWEEN 1 AND 200 AND octet_length(original_file_name) <= 255");

                            t.HasCheckConstraint("ck_legal_documents_size_bytes", "size_bytes BETWEEN 1 AND 26214400");

                            t.HasCheckConstraint("ck_legal_documents_stored_object_key", "stored_object_key ~ '^[0-9a-f]{32}$'");
                        });
                });

            modelBuilder.Entity("Enma.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CalendarEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("calendar_event_id");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<Guid?>("LegalDeadlineId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_deadline_id");

                    b.Property<Guid?>("LegalTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_task_id");

                    b.Property<DateTimeOffset?>("OccurrenceAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurrence_at");

                    b.Property<DateOnly?>("OccurrenceDate")
                        .HasColumnType("date")
                        .HasColumnName("occurrence_date");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("OrganizationId", "RecipientUserId")
                        .HasDatabaseName("ix_notifications_organization_id_recipient_user_id");

                    b.HasIndex("OrganizationId", "CalendarEventId", "RecipientUserId", "Kind", "OccurrenceAt")
                        .IsUnique()
                        .HasDatabaseName("ux_notifications_calendar_event_dedupe")
                        .HasFilter("calendar_event_id IS NOT NULL");

                    b.HasIndex("OrganizationId", "LegalDeadlineId", "RecipientUserId", "Kind", "OccurrenceDate")
                        .IsUnique()
                        .HasDatabaseName("ux_notifications_deadline_dedupe")
                        .HasFilter("legal_deadline_id IS NOT NULL");

                    b.HasIndex("OrganizationId", "LegalTaskId", "RecipientUserId", "Kind", "OccurrenceDate")
                        .IsUnique()
                        .HasDatabaseName("ux_notifications_task_dedupe")
                        .HasFilter("legal_task_id IS NOT NULL");

                    b.ToTable("notifications", null, t =>
                        {
                            t.HasCheckConstraint("ck_notifications_exactly_one_source", "num_nonnulls(legal_deadline_id, legal_task_id, calendar_event_id) = 1");

                            t.HasCheckConstraint("ck_notifications_kind", "kind IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_notifications_kind_source", "(kind = 1 AND legal_deadline_id IS NOT NULL) OR (kind = 2 AND legal_task_id IS NOT NULL) OR (kind = 3 AND calendar_event_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_notifications_occurrence", "(kind IN (1, 2) AND occurrence_date IS NOT NULL AND occurrence_at IS NULL) OR (kind = 3 AND occurrence_date IS NULL AND occurrence_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_notifications_read_at", "read_at IS NULL OR read_at >= generated_at");
                        });
                });

            modelBuilder.Entity("Enma.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_organizations_slug");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Enma.Domain.Organizations.OrganizationMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_organization_memberships");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_organization_memberships_organization_id_id");

                    b.HasAlternateKey("OrganizationId", "UserId")
                        .HasName("ux_organization_memberships_organization_id_user_id");

                    b.HasAlternateKey("OrganizationId", "Id", "UserId")
                        .HasName("ak_organization_memberships_organization_id_id_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_organization_memberships_user_id");

                    b.ToTable("organization_memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_organization_memberships_role", "role IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Enma.Domain.Processes.LegalProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_legal_processes");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_legal_processes_organization_id_id");

                    b.HasIndex("OrganizationId", "ClientId")
                        .HasDatabaseName("ix_legal_processes_organization_id_client_id");

                    b.ToTable("legal_processes", (string)null);
                });

            modelBuilder.Entity("Enma.Domain.Tasks.LegalTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_membership_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_membership_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_legal_tasks");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_legal_tasks_organization_id_id");

                    b.HasIndex("OrganizationId", "CreatedByMembershipId")
                        .HasDatabaseName("ix_legal_tasks_organization_id_created_by_membership_id");

                    b.HasIndex("DueDate", "OrganizationId", "Id")
                        .HasDatabaseName("ix_legal_tasks_pending_due_date_organization_id_id")
                        .HasFilter("completed_at IS NULL AND due_date IS NOT NULL");

                    b.HasIndex("OrganizationId", "CompletedAt", "Id")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("ix_legal_tasks_completed_organization_completed_at_id")
                        .HasFilter("completed_at IS NOT NULL");

                    b.HasIndex("OrganizationId", "DueDate", "CreatedAt", "Id")
                        .IsDescending(false, false, true, false)
                        .HasDatabaseName("ix_legal_tasks_pending_organization_due_date_created_at_id")
                        .HasFilter("completed_at IS NULL");

                    b.HasIndex("OrganizationId", "AssigneeMembershipId", "DueDate", "CreatedAt", "Id")
                        .IsDescending(false, false, false, true, false)
                        .HasDatabaseName("ix_legal_tasks_pending_org_assignee_due_date_created_at_id")
                        .HasFilter("completed_at IS NULL");

                    b.HasIndex("OrganizationId", "ProcessId", "DueDate", "CreatedAt", "Id")
                        .IsDescending(false, false, false, true, false)
                        .HasDatabaseName("ix_legal_tasks_pending_org_process_due_date_created_at_id")
                        .HasFilter("completed_at IS NULL");

                    b.ToTable("legal_tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_legal_tasks_completion", "completed_at IS NULL OR completed_at >= created_at");

                            t.HasCheckConstraint("ck_legal_tasks_description_normalized", "description IS NULL OR (description = btrim(description) AND length(description) > 0)");

                            t.HasCheckConstraint("ck_legal_tasks_title_normalized", "title = btrim(title) AND length(title) > 0");
                        });
                });

            modelBuilder.Entity("Enma.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_email_verified_at", "email_verified_at IS NULL OR email_verified_at >= created_at");
                        });
                });

            modelBuilder.Entity("Enma.Domain.Users.UserCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CredentialVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("credential_version");

                    b.Property<DateTimeOffset>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("UserId")
                        .HasName("pk_user_credentials");

                    b.ToTable("user_credentials", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_credentials_credential_version", "credential_version > 0");

                            t.HasCheckConstraint("ck_user_credentials_password_changed_at", "password_changed_at >= created_at");
                        });
                });

            modelBuilder.Entity("Enma.Infrastructure.Persistence.EmailVerificationSendBudget", b =>
                {
                    b.Property<short>("Scope")
                        .HasColumnType("smallint")
                        .HasColumnName("scope");

                    b.Property<byte[]>("KeyHash")
                        .HasColumnType("bytea")
                        .HasColumnName("key_hash");

                    b.Property<int>("Used")
                        .HasColumnType("integer")
                        .HasColumnName("used");

                    b.Property<DateTimeOffset>("WindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start");

                    b.HasKey("Scope", "KeyHash")
                        .HasName("pk_email_verification_send_budgets");

                    b.ToTable("email_verification_send_budgets", null, t =>
                        {
                            t.HasCheckConstraint("ck_email_verification_send_budgets_key_hash_length", "octet_length(key_hash) = 32");

                            t.HasCheckConstraint("ck_email_verification_send_budgets_scope", "scope IN (1, 2)");

                            t.HasCheckConstraint("ck_email_verification_send_budgets_used", "used > 0");

                            t.HasCheckConstraint("ck_email_verification_send_budgets_window_start", "isfinite(window_start)");
                        });
                });

            modelBuilder.Entity("Enma.Domain.Auditing.AuditLog", b =>
                {
                    b.HasOne("Enma.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_organizations_organization_id");

                    b.HasOne("Enma.Domain.Organizations.OrganizationMembership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ActorMembershipId", "ActorUserId")
                        .HasPrincipalKey("OrganizationId", "Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_memberships_org_membership_user_id");
                });

            modelBuilder.Entity("Enma.Domain.Authentication.AuthenticationSession", b =>
                {
                    b.HasOne("Enma.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_authentication_sessions_users_user_id");
                });

            modelBuilder.Entity("Enma.Domain.Authentication.EmailVerificationChallenge", b =>
                {
                    b.HasOne("Enma.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Enma.Domain.Authentication.EmailVerificationChallenge", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_verification_challenges_users_user_id");
                });

            modelBuilder.Entity("Enma.Domain.CalendarEvents.CalendarEvent", b =>
                {
                    b.HasOne("Enma.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_events_organizations_organization_id");

                    b.HasOne("Enma.Domain.Organizations.OrganizationMembership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "AssigneeMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_calendar_events_memberships_org_assignee_membership_id");

                    b.HasOne("Enma.Domain.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ClientId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_calendar_events_clients_organization_id_client_id");

                    b.HasOne("Enma.Domain.Organizations.OrganizationMembership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CreatedByMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_events_memberships_org_created_by_membership_id");

                    b.HasOne("Enma.Domain.Processes.LegalProcess", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ProcessId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_calendar_events_processes_organization_id_process_id");
                });

            modelBuilder.Entity("Enma.Domain.Clients.Client", b =>
                {
                    b.HasOne("Enma.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clients_organizations_organization_id");
                });

            modelBuilder.Entity("Enma.Domain.Deadlines.LegalDeadline", b =>
                {
                    b.HasOne("Enma.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_legal_deadlines_organizations_organization_id");

                    b.HasOne("Enma.Domain.Processes.LegalProcess", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ProcessId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_legal_deadlines_legal_processes_organization_id_process_id");
                });

            modelBuilder.Entity("Enma.Domain.Documents.LegalDocument", b =>
                {
                    b.HasOne("Enma.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_legal_documents_organizations_organization_id");

                    b.HasOne("Enma.Domain.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ClientId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_legal_documents_clients_org_id_client_id");

                    b.HasOne("Enma.Domain.Processes.LegalProcess", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ProcessId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_legal_documents_processes_org_id_process_id");

                    b.HasOne("Enma.Domain.Organizations.OrganizationMembership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "UploadedByMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_legal_documents_memberships_org_id_uploader_id");
                });

            modelBuilder.Entity("Enma.Domain.Notifications.Notification", b =>
                {
                    b.HasOne("Enma.Domain.CalendarEvents.CalendarEvent", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CalendarEventId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_notifications_calendar_events_org_calendar_event_id");

                    b.HasOne("Enma.Domain.Deadlines.LegalDeadline", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "LegalDeadlineId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_notifications_deadlines_org_legal_deadline_id");

                    b.HasOne("Enma.Domain.Tasks.LegalTask", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "LegalTaskId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_notifications_tasks_org_legal_task_id");

                    b.HasOne("Enma.Domain.Organizations.OrganizationMembership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "RecipientUserId")
                        .HasPrincipalKey("OrganizationId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_memberships_org_recipient_user_id");
                });

            modelBuilder.Entity("Enma.Domain.Organizations.OrganizationMembership", b =>
                {
                    b.HasOne("Enma.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_memberships_organizations_organization_id");

                    b.HasOne("Enma.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_memberships_users_user_id");
                });

            modelBuilder.Entity("Enma.Domain.Processes.LegalProcess", b =>
                {
                    b.HasOne("Enma.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_legal_processes_organizations_organization_id");

                    b.HasOne("Enma.Domain.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ClientId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_legal_processes_clients_organization_id_client_id");
                });

            modelBuilder.Entity("Enma.Domain.Tasks.LegalTask", b =>
                {
                    b.HasOne("Enma.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_legal_tasks_organizations_organization_id");

                    b.HasOne("Enma.Domain.Organizations.OrganizationMembership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "AssigneeMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_legal_tasks_memberships_org_assignee_membership_id");

                    b.HasOne("Enma.Domain.Organizations.OrganizationMembership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CreatedByMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_legal_tasks_memberships_org_created_by_membership_id");

                    b.HasOne("Enma.Domain.Processes.LegalProcess", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ProcessId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_legal_tasks_legal_processes_organization_id_process_id");
                });

            modelBuilder.Entity("Enma.Domain.Users.UserCredential", b =>
                {
                    b.HasOne("Enma.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Enma.Domain.Users.UserCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_credentials_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
