// <auto-generated />
using System;
using Enma.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Enma.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EnmaDbContext))]
    [Migration("20260814183645_AddLegalTasks")]
    partial class AddLegalTasks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Enma.Domain.Authentication.AuthenticationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expires_at");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CredentialVersionAtIssue")
                        .HasColumnType("bigint")
                        .HasColumnName("credential_version_at_issue");

                    b.Property<DateTimeOffset>("IdleExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("idle_expires_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_authentication_sessions");

                    b.HasIndex("AbsoluteExpiresAt")
                        .HasDatabaseName("ix_authentication_sessions_absolute_expires_at");

                    b.HasIndex("IdleExpiresAt")
                        .HasDatabaseName("ix_authentication_sessions_idle_expires_at");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("ux_authentication_sessions_secret_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_authentication_sessions_user_id");

                    b.ToTable("authentication_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_authentication_sessions_absolute_expires_at", "absolute_expires_at > created_at");

                            t.HasCheckConstraint("ck_authentication_sessions_concurrency_version", "concurrency_version > 0");

                            t.HasCheckConstraint("ck_authentication_sessions_credential_version_at_issue", "credential_version_at_issue > 0");

                            t.HasCheckConstraint("ck_authentication_sessions_idle_expires_at", "idle_expires_at > last_seen_at AND idle_expires_at <= absolute_expires_at");

                            t.HasCheckConstraint("ck_authentication_sessions_last_seen_at", "last_seen_at >= created_at");

                            t.HasCheckConstraint("ck_authentication_sessions_revoked_at", "revoked_at IS NULL OR revoked_at >= created_at");

                            t.HasCheckConstraint("ck_authentication_sessions_secret_hash_length", "octet_length(secret_hash) = 32");
                        });
                });

            modelBuilder.Entity("Enma.Domain.Authentication.EmailVerificationChallenge", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailAtIssue")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email_at_issue");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.HasKey("UserId")
                        .HasName("pk_email_verification_challenges");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_email_verification_challenges_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_email_verification_challenges_token_hash");

                    b.ToTable("email_verification_challenges", null, t =>
                        {
                            t.HasCheckConstraint("ck_email_verification_challenges_expiration", "expires_at > created_at");

                            t.HasCheckConstraint("ck_email_verification_challenges_token_hash_length", "octet_length(token_hash) = 32");
                        });
                });

            modelBuilder.Entity("Enma.Domain.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_clients_organization_id_id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Enma.Domain.Deadlines.LegalDeadline", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_legal_deadlines");

                    b.HasIndex("OrganizationId", "DueDate", "Id")
                        .HasDatabaseName("ix_legal_deadlines_organization_id_due_date_id");

                    b.HasIndex("OrganizationId", "ProcessId", "DueDate", "Id")
                        .HasDatabaseName("ix_legal_deadlines_organization_id_process_id_due_date_id");

                    b.ToTable("legal_deadlines", null, t =>
                        {
                            t.HasCheckConstraint("ck_legal_deadlines_completion", "completed_at IS NULL OR completed_at >= created_at");

                            t.HasCheckConstraint("ck_legal_deadlines_title_normalized", "title = btrim(title) AND title <> ''");
                        });
                });

            modelBuilder.Entity("Enma.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_organizations_slug");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Enma.Domain.Organizations.OrganizationMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_organization_memberships");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_organization_memberships_organization_id_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_organization_memberships_user_id");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_organization_memberships_organization_id_user_id");

                    b.ToTable("organization_memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_organization_memberships_role", "role IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Enma.Domain.Processes.LegalProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_legal_processes");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_legal_processes_organization_id_id");

                    b.HasIndex("OrganizationId", "ClientId")
                        .HasDatabaseName("ix_legal_processes_organization_id_client_id");

                    b.ToTable("legal_processes", (string)null);
                });

            modelBuilder.Entity("Enma.Domain.Tasks.LegalTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_membership_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_membership_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_legal_tasks");

                    b.HasIndex("OrganizationId", "CreatedByMembershipId")
                        .HasDatabaseName("ix_legal_tasks_organization_id_created_by_membership_id");

                    b.HasIndex("OrganizationId", "CompletedAt", "Id")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("ix_legal_tasks_completed_organization_completed_at_id")
                        .HasFilter("completed_at IS NOT NULL");

                    b.HasIndex("OrganizationId", "DueDate", "CreatedAt", "Id")
                        .IsDescending(false, false, true, false)
                        .HasDatabaseName("ix_legal_tasks_pending_organization_due_date_created_at_id")
                        .HasFilter("completed_at IS NULL");

                    b.HasIndex("OrganizationId", "AssigneeMembershipId", "DueDate", "CreatedAt", "Id")
                        .IsDescending(false, false, false, true, false)
                        .HasDatabaseName("ix_legal_tasks_pending_org_assignee_due_date_created_at_id")
                        .HasFilter("completed_at IS NULL");

                    b.HasIndex("OrganizationId", "ProcessId", "DueDate", "CreatedAt", "Id")
                        .IsDescending(false, false, false, true, false)
                        .HasDatabaseName("ix_legal_tasks_pending_org_process_due_date_created_at_id")
                        .HasFilter("completed_at IS NULL");

                    b.ToTable("legal_tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_legal_tasks_completion", "completed_at IS NULL OR completed_at >= created_at");

                            t.HasCheckConstraint("ck_legal_tasks_description_normalized", "description IS NULL OR (description = btrim(description) AND length(description) > 0)");

                            t.HasCheckConstraint("ck_legal_tasks_title_normalized", "title = btrim(title) AND length(title) > 0");
                        });
                });

            modelBuilder.Entity("Enma.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_email_verified_at", "email_verified_at IS NULL OR email_verified_at >= created_at");
                        });
                });

            modelBuilder.Entity("Enma.Domain.Users.UserCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CredentialVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("credential_version");

                    b.Property<DateTimeOffset>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("UserId")
                        .HasName("pk_user_credentials");

                    b.ToTable("user_credentials", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_credentials_credential_version", "credential_version > 0");

                            t.HasCheckConstraint("ck_user_credentials_password_changed_at", "password_changed_at >= created_at");
                        });
                });

            modelBuilder.Entity("Enma.Infrastructure.Persistence.EmailVerificationSendBudget", b =>
                {
                    b.Property<short>("Scope")
                        .HasColumnType("smallint")
                        .HasColumnName("scope");

                    b.Property<byte[]>("KeyHash")
                        .HasColumnType("bytea")
                        .HasColumnName("key_hash");

                    b.Property<int>("Used")
                        .HasColumnType("integer")
                        .HasColumnName("used");

                    b.Property<DateTimeOffset>("WindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start");

                    b.HasKey("Scope", "KeyHash")
                        .HasName("pk_email_verification_send_budgets");

                    b.ToTable("email_verification_send_budgets", null, t =>
                        {
                            t.HasCheckConstraint("ck_email_verification_send_budgets_key_hash_length", "octet_length(key_hash) = 32");

                            t.HasCheckConstraint("ck_email_verification_send_budgets_scope", "scope IN (1, 2)");

                            t.HasCheckConstraint("ck_email_verification_send_budgets_used", "used > 0");

                            t.HasCheckConstraint("ck_email_verification_send_budgets_window_start", "isfinite(window_start)");
                        });
                });

            modelBuilder.Entity("Enma.Domain.Authentication.AuthenticationSession", b =>
                {
                    b.HasOne("Enma.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_authentication_sessions_users_user_id");
                });

            modelBuilder.Entity("Enma.Domain.Authentication.EmailVerificationChallenge", b =>
                {
                    b.HasOne("Enma.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Enma.Domain.Authentication.EmailVerificationChallenge", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_verification_challenges_users_user_id");
                });

            modelBuilder.Entity("Enma.Domain.Clients.Client", b =>
                {
                    b.HasOne("Enma.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clients_organizations_organization_id");
                });

            modelBuilder.Entity("Enma.Domain.Deadlines.LegalDeadline", b =>
                {
                    b.HasOne("Enma.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_legal_deadlines_organizations_organization_id");

                    b.HasOne("Enma.Domain.Processes.LegalProcess", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ProcessId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_legal_deadlines_legal_processes_organization_id_process_id");
                });

            modelBuilder.Entity("Enma.Domain.Organizations.OrganizationMembership", b =>
                {
                    b.HasOne("Enma.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_memberships_organizations_organization_id");

                    b.HasOne("Enma.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_memberships_users_user_id");
                });

            modelBuilder.Entity("Enma.Domain.Processes.LegalProcess", b =>
                {
                    b.HasOne("Enma.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_legal_processes_organizations_organization_id");

                    b.HasOne("Enma.Domain.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ClientId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_legal_processes_clients_organization_id_client_id");
                });

            modelBuilder.Entity("Enma.Domain.Tasks.LegalTask", b =>
                {
                    b.HasOne("Enma.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_legal_tasks_organizations_organization_id");

                    b.HasOne("Enma.Domain.Organizations.OrganizationMembership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "AssigneeMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_legal_tasks_memberships_org_assignee_membership_id");

                    b.HasOne("Enma.Domain.Organizations.OrganizationMembership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CreatedByMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_legal_tasks_memberships_org_created_by_membership_id");

                    b.HasOne("Enma.Domain.Processes.LegalProcess", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ProcessId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_legal_tasks_legal_processes_organization_id_process_id");
                });

            modelBuilder.Entity("Enma.Domain.Users.UserCredential", b =>
                {
                    b.HasOne("Enma.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Enma.Domain.Users.UserCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_credentials_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
